config/routes.rb
Rails.application.routes.draw do

  get  '/:id', to: 'sites#show', as: 'main', constraints: { id: /[^\/]+/ }
  patch   '/:id',   to: 'sites#add_password', as: 'site_pass'
  patch   '/d/:id',   to: 'sites#remove_password', as: 'd_site_pass'

  resources :posts, only: [:create, :destroy]

  post   '/unlock',   to: 'sessions#create', as: 'unlock'
  delete '/logout/:id',  to: 'sessions#destroy', as: 'logout'

  root 'sites#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :site
  
end

app/models/site.rb
class Site < ApplicationRecord
  before_create :lock_init
  VALID_NAME_REGEX = /\A[a-zA-Z\d\-]+\z/i # letters, numbers, dashes
  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }, format: { with: VALID_NAME_REGEX }
  has_secure_password validations: false
  has_many :posts, dependent: :destroy

  private

    # when sites are created, they should be public
    def lock_init
      self.locked = false
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SitesHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :editable?, only: [:create]
  before_action :deletable?, only: [:destroy]
  after_action :no_posts?, only: [:destroy]

  def create

    @site = Site.find_by(name: params[:post][:site])
    @post = @site.posts.build(post_params)

    if @post.save
      redirect_to main_path(@post.site.name)
    else
      render 'sites/show'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @site = @post.site
    @post.destroy
    flash[:success] = "Post deleted"
    redirect_to main_path(@site.name)
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end

  def editable?
    @slug = params[:post][:site]
    @site = Site.find_by(name: @slug)
    if private?
      redirect_to main_path(@site.name), notice: 'Site is locked.'
    end
  end

  def deletable?
    @post = Post.find(params[:id])
    @site = @post.site
    if private?
      redirect_to main_path(@site.name), notice: 'Site is locked.'
    end
  end

  def clean_links html
   html.gsub(/\<a href=["'](.*?)["']\>(.*?)\<\/a\>/mi, '<a href="\1" rel="nofollow ugc" target="_new" >\2</a>')
  end

  def no_posts?
    if @site.locked && @site.posts.count == 0
      session.delete(@site.name.to_sym)
      @site.update_attributes(locked: false)
      flash[:notice] = "Empty site, so password removed :)"
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    site = Site.find_by(name: params[:session][:site])
    if site && site.authenticate(params[:session][:password])
      session[site.name.to_sym] = "session-unlocked"
      redirect_to main_path(site.name), notice: 'Logged in. Free to add/delete posts'
    else
      flash.now[:danger] = 'Invalid password'
      redirect_to main_path(site.name), notice: 'Incorrect password'
    end
  end

  def destroy
    site_name = params[:id]
    session.delete(site_name)
    redirect_to main_path(site_name), notice: 'Logged out'
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :find_site, only: [:show, :add_password, :remove_password]
  before_action :unlocked?, only: [:add_password, :remove_password]
  before_action :have_posts?, only: [:add_password]

  def show

    if @site.nil?
      @site = Site.new(name: @slug)
      if @site.save
        flash.now[:notice] = "Your site is ready.  Hi #{@slug} :)"
      else
        redirect_to main_path("faq"), alert: "Site not saved. Letter, numbers, and dashes accepted."
      end
    end

    @feed = @site.posts.order("created_at DESC")

  end

  def home
    @slug = ('a'..'z').to_a.shuffle[0,8].join
    redirect_to main_path(@slug)
  end

  def add_password
    if @site.update_attributes(pass_params)
      lock_site
      redirect_to site_pass_path(@site.name), notice: "Updated password"
    else
      redirect_to site_pass_path(@site.name), alert: "Update failed"
    end
  end

  def remove_password
    if unlock_site
      redirect_to site_pass_path(@site.name), notice: "Removed password"
    else
      redirect_to site_pass_path(@site.name), alert: "Update failed"
    end
  end

  private


    def pass_params
      params.require(:site).permit(:password, :password_confirmation)
    end

    def find_site
      @slug = params[:id].downcase
      @site = Site.find_by(name: @slug)
      if @site.present?
        expired?
      end
    end

    def lock_site
      @site.update_attributes(locked: true)
    end

    def unlock_site
      session.delete(@site.name.to_sym)
      @site.update_attributes(locked: false)
    end

    def unlocked?
      if private?
        redirect_to main_path(@site.name), notice: 'Site is locked.'
      end
    end

    def have_posts?
      if @site.posts.count == 0
        redirect_to main_path(@site.name), notice: 'Cannot add password to empty site.'
      end
    end


    def expired?
      last_post = @site.posts.last
      if last_post.present?
        activity_limit = 31
        @days_til_expire = activity_limit - (Time.zone.now - last_post.updated_at)/(3600*24)
        if @days_til_expire < 0
          @site.destroy
          redirect_to main_path(@site.name), notice: 'Previous site here was deleted due to inactivity.'
        end
      end
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def clean_links html
    html.gsub!(/\<a href=["'](.*?)["']\>(.*?)\<\/a\>/mi, '<a href="\1" rel="nofollow ugc">\2</a>')
    html.html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
end

app/helpers/sites_helper.rb
module SitesHelper
  def postable?
    !@site.locked || (@site.locked && session[@site.name.to_sym] == "session-unlocked")
  end

  def private?
    @site.locked && session[@site.name.to_sym] != "session-unlocked"
  end

  def logged_in?
    session[@site.name.to_sym] == "session-unlocked" && @site.locked
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% if Rails.env.production? %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-32951228-7"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-32951228-7');
      document.addEventListener('turbolinks:load', event => {
          if (typeof gtag === 'function') {
            gtag('config', 'UA-32951228-7', {
              'page_location': event.data.url
            });
          }
        });
    </script>
    <% end %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" >
    <%= favicon_link_tag asset_path('fav.png') %>

  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/posts/_feed.html.erb
<ul id="feed">
<% @feed.each do |item| %>
  <li class="box">
    <%= clean_links simple_format(item.body) %>
    <div class="date is-size-7 has-text-grey"><%= local_time(item.created_at.to_formatted_s(:short), '%b %e') %></div>
    <% if !@site.locked || (@site.locked && session[@site.name.to_sym] == "session-unlocked") %>
      <%= link_to "Delete", post_path(item.id), data: { confirm: "Are you sure?" }, method: :delete, class: "delete is-small" %>
    <% end %>
  </li>
<% end %>
</ul>

app/views/posts/_new_post.html.erb
<%= form_for Post.new, :html => {:class => ''} do |f| %>

  <%= f.text_area :body , class: "textarea is-small", rows:3 %>
  <%= f.hidden_field :site, value: @site.name %>
  <%= f.submit "Post", class: "button is-light post" %>

<% end %>

app/views/shared/_error_messages.html.erb
<% if @site.errors.any? %>
  <div>
    The form contains <%= pluralize(@site.errors.count, "error") %>.
    <ul>
    <% @site.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/sites/_addpass.html.erb
<% if !@site.locked && @feed.present? %>
<div class="dropdown-item">
  <%= form_for @site, url: site_pass_path(@site.name), :html => {:class => ''}, method: :patch do |f| %>
  <div class="field has-addons">
    <div class="control">
    <%= f.password_field :password, required:true, class: "input" %>
    </div>
    <div class="control">
    <%= f.submit "Add password", class: "button" %>
    </div>
  </div>
  <% end %>
</div>
<hr class="dropdown-divider">

<% end %>

app/views/sites/_intro.html.erb
<% if  @feed.empty? && !@site.locked %>
<div class="dropdown-item">
Password can be added after first post
</div>
<% end %>

app/views/sites/_login.html.erb
<% if private?%>
<div class="dropdown-item">
  <%= form_for(:session, url: unlock_path) do |f| %>
  <%= f.hidden_field :site, value: @site.name %>
  <div class="field has-addons">
    <div class="control">
      <%= f.password_field :password, class: "input" %>
    </div>
    <div class="control">
      <%= f.submit "Login" , class: "button" %>
    </div>
  </div>
  <% end %>
</div>
<hr class="dropdown-divider">
<% end %>

app/views/sites/_meta_info.html.erb
<div id="meta-info">

  <div class="dropdown is-up">
    <div class="dropdown-trigger">
      <button class="button is-white" aria-haspopup="true" >
        <span class="icon has-text-dark">
          <i class="fas fa-info-circle"></i>
        </span>
      </button>
    </div>
    <div class="dropdown-menu">
      <div class="dropdown-content">
        <%= render 'when-locked'  %>
        <%= render 'login'  %>
        <%= render 'addpass' %>
        <%= render 'intro' %>
        <% if @feed.present? %>
          <div class="dropdown-item">
            <p id="expire"><%= @days_til_expire.to_i %> days until self-destruction</p>
            <p class="has-text-grey">Site is deleted after 30 days of inactivity</p>
          </div>
        <% end %>
        <hr class="dropdown-divider">
        <div class="dropdown-item">
          <a href="/faq" target="_blank">FAQ</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sites/_update_body.html.erb
<%= form_for @site, url: site_body_path(@site.name), method: :patch do |f| %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit "Save changes" %>

<% end %>

app/views/sites/_when-locked.html.erb
<% if @site.locked %>

      <% if logged_in? %>
      <div class="dropdown-item">
        <%= button_to "Logout", logout_path(@site.name), class: "button remove is-light", method: :delete %>
       </div>
       <hr class="dropdown-divider">
      <div class="dropdown-item">
        <%= button_to "Remove password", d_site_pass_path(@site.name), data: { confirm: "Are you sure? Anyone will be able to add posts." }, class: "button remove is-light", method: :patch %>
       </div>
       <hr class="dropdown-divider">
     <% end %>
  <% else %>


<% end %>

app/views/sites/show.html.erb
<% provide(:title, @site.name) %>
<section id="meta">
  <header>
    <span class="has-text-grey-light">/</span>
    <strong class=""><%= @site.name %></strong>
  </header>
  <%= render 'posts/new_post' if postable? %>
  <%= render 'meta_info' %>

</section>

<section id="content" >
  <%= render 'shared/error_messages' %>
  <% if notice %>
      <p class="notification is-warning"><button class="delete"></button><%= notice %></p>
  <% end %>
  <% if alert %>
      <p class="notification is-danger"><button class="delete"></button><%= alert %></p>
  <% end %>

  <%= render 'posts/feed' %>

</section>

app/views/sites/temp.html.erb
<p>this is temp!</p>
<p>this is used to test the params passed when posting</p>
<em>#render 'sites/temp'</em>